       name: Step 4, Open a Pull Request

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          if [ -f ./.github/steps/-step.txt ]; then
            echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
          else
            echo "current_step=0" >> $GITHUB_OUTPUT
          fi
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_pr_opened:
    name: On PR from update-game to main
    needs: get_current_step
    if: >-
      ${{
        !github.event.repository.is_template &&
        needs.get_current_step.outputs.current_step == '4' &&
        github.event.pull_request.head.ref == 'update-game' &&
        github.event.pull_request.base.ref == 'main'
      }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: update-game

      - name: Update to step 5
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 4
          to_step: 5
          branch_name: update-game
