name: Step 4, Open a Pull Request

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize  # use this instead of 'submitted'

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  update_to_step_5:
    name: Update to Step 5 when PR is opened or submitted
    needs: get_current_step
    if: >-
      ${{ 
        !github.event.repository.is_template &&
        needs.get_current_step.outputs.current_step == '4' &&
        github.event.pull_request.head.ref == 'update-game' &&
        github.event.pull_request.base.ref == 'main'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout update-game branch
        uses: actions/checkout@v4
        with:
          ref: update-game
          fetch-depth: 0

      - name: Update step number file
        run: echo "5" > ./.github/steps/-step.txt

      - name: Commit and push updated step file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./.github/steps/-step.txt
          git commit -m "Update to step 5"
          git push

      - name: Add success comment to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const eventType = context.payload.action;
            let message = '';

            if (eventType === 'opened' || eventType === 'reopened') {
              message = '🎉 Great job opening a pull request! You have completed Step 4 and can now move on to Step 5: Link and Merge the Pull Request.';
            } else {
              message = '🎉 You have completed Step 4 and can now move on to Step 5: Link and Merge the Pull Request.';
            }

            message += '\n\nIn Step 5, you will learn how to link this PR to an issue and then merge it into the main branch.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
